export default [
    'Director',
    'Nurse',
    'Lawyer',
    'Innovation Specialist',
    'Digital Transformation Officer',
    'Product Strategist',
    'Brand Experience Lead',
    'Customer Insights Analyst',
    'Culture and Engagement Manager',
    'Technology Evangelist',
    'Agile Enablement Lead',
    'Future Trends Analyst',
    'Solutions Consultant',
    'Experience Designer',
    'Strategic Growth Manager',
    'Chief Vision Officer',
]
