export { PersonalTab } from './personal'
export { DeductionsAndLoansTab } from './customDeductions'
export { JobInfoTab } from './job'
export { DepositAccountTab } from './depositAccounts'
export { BenefitsTab } from './benefits'
export { BonusesTab } from './bonuses'
export { Reimbursements } from './reimbursement'
